### ISSUE TITLE
Develop Secondary version of Remote Dialog UI

### ISSUE THREAD

**Issue by mmehr2** [mmehr2/Msw4#20]
This needs to be a trimmed-down version of the Primary one, if at all.
It should show the net status and error indications that the Primary would (see issue #19) but remove all the rest of the complexity (only for the Primary version).

Depending on how the billable features work out, we may also want to have the Login/Logout button here to control when the Secondary will listen for connections, since this may increase billable message traffic if left on 24/7. See issue #16 for details.

**Comment by mmehr2** [comment]
Work tasks:

Decision: Actually, this can be just a login/logout button and status message panel. 
UPDATE 4/4: Even easier to use existing Primary dialog and hide or disable controls (Phase 0).

**Phase 1 (easy)**: Modify existing Primary Remote Dialog for Secondary use:

- [x] Disable and/or hide the bottom half of the dialog if not primary (Connect button and all the UI related to the management of the list of Secondaries). Shrink the dialog to fit.
- [x] Add the static text for display of the status message. Display position adjust Primary/Secondary.
- [x] Auto-disable the Login/out button when pressed
- [x] Modify the message handler to display the message and re-enable Login button.

**Phase 2 (if time):** It may be better to integrate this into the main UI. 

- [ ] Put the Secondary Login button onto the Toolbar, leaving the Remote Installations dialog for remote access (primary only).
- [ ] Use the status line at the bottom for one-line status messages. -OR-
- [ ] Place the status message somewhere else on the Toolbar
- [ ] And maybe add an indicator similar to CAPS and NUM on the bottom right for ONLINE (secondary when listening, PAIRED for primary and secondary when connected).

**Comment by mmehr2** [comment]
I have decided to dynamically modify the RemoteDialog layout depending on configuration (Primary, Secondary). In Secondary mode, the controls for the list management and Connect are hidden, and the Network Message box and the Close button (IDOK) are moved up. Finally, the height of the dialog is shrunk to fit the controls' new positions.

I had a bear of a time getting docs on which of the functions (SetWindowPos, MoveWindow, GetClientRect, GetWindowRect) to use, and what units they return. I had to use some fudge factors, which will probably look bad on other resolutions. Need to work this out better, but for now just make sure the buttons are usable on as many resolutions as possible for me to test here. And Eric later.
