### ISSUE TITLE
Adding installer and full build to repo

### ISSUE THREAD

**Issue by mmehr2** [mmehr2/Msw4#8]
Somehow the various changes to the 3rd Party files need to be tracked. Pubnub may be scrapped, however.

And lots of binaries won't fit well with Git's strengths. Let's consider the alternatives anyway.

**Comment by mmehr2** [comment]
Currently handled by holding the files on Google Drive, but no versioning is being done. I've made little changes to libjingle and added pubnub to 3rd Party, but haven't really worked on installer issues.

Probably put this as Won't Fix, but realize it's an issue.

**Comment by mmehr2** [comment]
Work tasks:
- Installer changes needed
-- Add the MSW.INI file? Or make this to use registry settings. Determine upgrade policies here (don't clobber keys or device names)
-- Primary and Secondary installers and their binaries.
- **QUESTION:** Do I deliver .MSI files? Decide what is deliverable here.
- **QUESTION:** How much of the source code needs to be tracked here? Do I use submodules? Or just include parts of the Install subtree that are modifiable, like the Inno Setup scripts? Inno Setup source code itself (probably not)?

**Comment by mmehr2** [comment]
Work tasks:
As each other issue generates install requirements, list them here.

- [x] - Changes to registry instead of direct use of INI file. (Just use it to load in new changes 1st time.)
- [ ] - (Issue #19 ) Install script for Primary to set the hidden registry flag for Primary behavior
- [ ] - (Issue #10 ) OpenSSL support - add in the two runtime DLL files that aren't part of the system (do they need versioning?)
- [ ] - (Issue #6 ) Support the Event Logger manifest install for Debugging (Admin privileges required)
